### ISSUE TITLE
Confirmação de Cadastro de Item

### ISSUE THREAD

**Issue by marcellmarra** [pedro-hos/ciclovias#2]
Limpar os dados e exibir mensagem de confirmação, redirecionando para a visualização do item dentro do mapa (?)

**Comment by pedro-hos** [comment]
![screenshot from 2018-07-31 09-42-33](https://user-images.githubusercontent.com/8390247/43460122-1671641c-94a6-11e8-8a20-69f3ffb6bfab.png)

**Comment by pedro-hos** [comment]
Ainda faltam alguns ajustes nessa tela, mas acho que esta ok por enquanto

**Comment by pedro-hos** [comment]
Message de erro tb

**Comment by pedro-hos** [comment]
finished!
