### ISSUE TITLE
Conteúdo: Quem Somos?

### ISSUE THREAD

**Issue by marcellmarra** [pedro-hos/ciclovias#4]
Sugestão

Somos uma iniciativa de pessoas que querem andar livremente com seus variados tipos de modais por todas as cidades do Brasil. O objetivo dessa ferramenta é dar visibilidade à necessidades de manutenção, reparação e até mesmo a criação de ciclovias, questões presenciados durante nossas locomoções pela cidade.

Equipe
Pedro Hos - Fodão, Agricultor e Codeiro
Marcell - mais um latino-americano

Apoio
Ciclistas de São José do Campos

**Comment by pedro-hos** [comment]
![screenshot from 2018-07-30 19-39-28](https://user-images.githubusercontent.com/8390247/43427527-4ff12cde-9430-11e8-9553-21e32fe2ec1d.png)
